// This file is generated by running the atlas_builder.
package game

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "../../assets/atlases/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {1028, 17, 10, 10}

Texture_Name :: enum {
	None,
	Tile,
	B_Block,
	Cloud_1,
	Background_Glacial_Mountains,
	Background_Cloudes,
	Cloud_2,
	Cloud_3,
	Cloud_4,
	Heart,
	Big_Lazer0,
	Big_Lazer1,
	Big_Lazer2,
	Big_Lazer3,
	Big_Lazer4,
	Big_Lazer5,
	Big_Lazer6,
	Big_Lazer7,
	Big_Lazer8,
	Big_Lazer9,
	Big_Lazer10,
	Big_Lazer11,
	Big_Lazer12,
	Big_Lazer13,
	Big_Lazer14,
	Big_Lazer15,
	Topple_Red,
	Topple,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Tile = { rect = {1062, 0, 16, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {16, 16}, duration = 0.100},
	.B_Block = { rect = {1028, 0, 16, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {16, 16}, duration = 0.100},
	.Cloud_1 = { rect = {770, 0, 128, 60}, offset_top = 4, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {128, 64}, duration = 0.100},
	.Background_Glacial_Mountains = { rect = {0, 0, 384, 205}, offset_top = 11, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {384, 216}, duration = 0.100},
	.Background_Cloudes = { rect = {385, 0, 384, 204}, offset_top = 12, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {384, 216}, duration = 0.100},
	.Cloud_2 = { rect = {867, 104, 96, 38}, offset_top = 3, offset_right = 0, offset_bottom = 7, offset_left = 0, document_size = {96, 48}, duration = 0.100},
	.Cloud_3 = { rect = {770, 104, 96, 38}, offset_top = 3, offset_right = 0, offset_bottom = 7, offset_left = 0, document_size = {96, 48}, duration = 0.100},
	.Cloud_4 = { rect = {899, 0, 128, 60}, offset_top = 4, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {128, 64}, duration = 0.100},
	.Heart = { rect = {1045, 0, 16, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {16, 16}, duration = 0.100},
	.Big_Lazer0 = { rect = {0, 222, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer1 = { rect = {513, 222, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer2 = { rect = {0, 239, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer3 = { rect = {513, 239, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer4 = { rect = {0, 256, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer5 = { rect = {0, 341, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer6 = { rect = {0, 273, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer7 = { rect = {513, 273, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer8 = { rect = {0, 290, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer9 = { rect = {513, 290, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer10 = { rect = {0, 307, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer11 = { rect = {513, 307, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer12 = { rect = {0, 324, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer13 = { rect = {513, 324, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer14 = { rect = {513, 256, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Big_Lazer15 = { rect = {385, 205, 512, 16}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {512, 16}, duration = 0.100},
	.Topple_Red = { rect = {770, 61, 107, 42}, offset_top = 6, offset_right = 2, offset_bottom = 0, offset_left = 3, document_size = {112, 48}, duration = 0.100},
	.Topple = { rect = {878, 61, 107, 42}, offset_top = 6, offset_right = 2, offset_bottom = 0, offset_left = 3, document_size = {112, 48}, duration = 0.100},
}

Animation_Name :: enum {
	None,
	Big_Lazer,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
	.Big_Lazer = { first_frame = .Big_Lazer0, last_frame = .Big_Lazer15, loop_direction = .Forward, repeat = 0, document_size = {512, 16} },
}

// All these are pre-generated so you can save tile IDs to data without
// worrying about their order changing later.
Tile_Id :: enum {
	T0Y0X0,
	T0Y0X1,
	T0Y0X2,
	T0Y0X3,
	T0Y0X4,
	T0Y0X5,
	T0Y0X6,
	T0Y0X7,
	T0Y0X8,
	T0Y0X9,
	T0Y1X0,
	T0Y1X1,
	T0Y1X2,
	T0Y1X3,
	T0Y1X4,
	T0Y1X5,
	T0Y1X6,
	T0Y1X7,
	T0Y1X8,
	T0Y1X9,
	T0Y2X0,
	T0Y2X1,
	T0Y2X2,
	T0Y2X3,
	T0Y2X4,
	T0Y2X5,
	T0Y2X6,
	T0Y2X7,
	T0Y2X8,
	T0Y2X9,
	T0Y3X0,
	T0Y3X1,
	T0Y3X2,
	T0Y3X3,
	T0Y3X4,
	T0Y3X5,
	T0Y3X6,
	T0Y3X7,
	T0Y3X8,
	T0Y3X9,
	T0Y4X0,
	T0Y4X1,
	T0Y4X2,
	T0Y4X3,
	T0Y4X4,
	T0Y4X5,
	T0Y4X6,
	T0Y4X7,
	T0Y4X8,
	T0Y4X9,
	T0Y5X0,
	T0Y5X1,
	T0Y5X2,
	T0Y5X3,
	T0Y5X4,
	T0Y5X5,
	T0Y5X6,
	T0Y5X7,
	T0Y5X8,
	T0Y5X9,
	T0Y6X0,
	T0Y6X1,
	T0Y6X2,
	T0Y6X3,
	T0Y6X4,
	T0Y6X5,
	T0Y6X6,
	T0Y6X7,
	T0Y6X8,
	T0Y6X9,
	T0Y7X0,
	T0Y7X1,
	T0Y7X2,
	T0Y7X3,
	T0Y7X4,
	T0Y7X5,
	T0Y7X6,
	T0Y7X7,
	T0Y7X8,
	T0Y7X9,
	T0Y8X0,
	T0Y8X1,
	T0Y8X2,
	T0Y8X3,
	T0Y8X4,
	T0Y8X5,
	T0Y8X6,
	T0Y8X7,
	T0Y8X8,
	T0Y8X9,
	T0Y9X0,
	T0Y9X1,
	T0Y9X2,
	T0Y9X3,
	T0Y9X4,
	T0Y9X5,
	T0Y9X6,
	T0Y9X7,
	T0Y9X8,
	T0Y9X9,
}

atlas_tiles := #partial [Tile_Id]Rect {
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
}
